### ISSUE TITLE
关于使用授权问题

### ISSUE THREAD

**Issue by DSOE1024** [sheep-realms/Echo-Live#1]
你好，请问这个项目可以用于商用游戏宣发宣传视频制作吗，需要在视频介绍备注什么吗

**Comment by DSOE1024** [comment]
> 你好，请问这个项目可以用于商用游戏宣发宣传视频制作吗，需要在视频介绍备注什么吗

**Comment by sheep-realms** [comment]
请参阅 [GPL-3.0 license](https://github.com/sheep-realms/Echo-Live/blob/master/LICENSE)
