### ISSUE TITLE
因HTML解析导致对话框中多个空格会被合并

### ISSUE THREAD

**Issue by RaySky-Rt** [sheep-realms/Echo-Live#2]
- [x] 我已确认 Echo-Live 的最新发行版本中依然存在此问题。
- [x] 我已确认近期没有其他人提出类似问题。

## 问题描述

我在输入时试图在一行文本中间通过一串空格（tab也试过）来将一行文本分隔为两小段，但是在插件中实际只会输出一个空格（如下文截图所示

这是我的start.js文件内容：

```
const data = {
    "username": ".", 
    "messages": [
        {
            "message": "「测试文本                  测试文本」",
            "data": {
                "printSpeed": "30"
            }
        }
    ]
}
```

我期望输出的：

```「测试文本                  测试文本」```

实际输出的：

```「测试文本 测试文本」```

## 期望效果

可以正常输出一长串空格

## 截图

![image](https://github.com/sheep-realms/Echo-Live/assets/66870364/3242d3d9-87da-440d-b3f0-a1d2dca2f5b2)

## 解决方案

我不知道.jpg（
无论往里面输多————长的空格（或者tab），它都只会显示一个（

**Comment by sheep-realms** [comment]
对话框内容基于 HTML 格式输出，因此一个或多个空字符会被替换成一个空格，建议试试全角空格。

这是一个正常现象，但不太符合直觉，我会尝试优化这个问题，但不保证能解决。

**Comment by RaySky-Rt** [comment]
全角空格的确可以解决问题，非常感谢（
期待后续更新

**Comment by sheep-realms** [comment]
漏洞正在处理。
另外您可能是刚刚使用 GitHub，请学习一下 Markdown 语法和 GitHub 的基本知识。这个问题未解决，请不要关闭。

**Comment by sheep-realms** [comment]
已通过为 Echo 增加过滤器修复了该问题，同时阻止了脚本注入。
