### ISSUE TITLE
建议增加背景透明度

### ISSUE THREAD

**Issue by saigouizayoi** [sheep-realms/Echo-Live#24]
- 我已确认 Echo-Live 近期没有类似更新。
- 我已确认近期没有其他人提出类似提议。

## 提议描述
如了个题，文本框可以设置下调节透明度，现在会完全遮蔽背景。
可以让文本背景有一定的透明度

p.s.:文本应该不用透明

## 实现方法
html的话是opacity属性就可以？

**Comment by sheep-realms** [comment]
主题样式文件位于 `res/style/live-theme/` 文件夹中，已预制了常用变量放在样式文件顶部，请根据需要自行修改。

以 `vanilla.css` 为例，截至 1.3.3 版本，你可以在第 39 行找到：

``` css
--echo-live-bg-color: #FFFFFF;
```

例如改成白色半透明：

``` css
--echo-live-bg-color: rgba(255, 255, 255, 0.5);
```

另外，如果想要全透明，请使用 `void` 主题。
