### ISSUE TITLE
关于编辑器页面中 Tab 焦点顺序的若干问题

### ISSUE THREAD

**Issue by Passthem-desu** [sheep-realms/Echo-Live#26]
- 我已确认 Echo-Live 近期没有类似更新。
- 我已确认近期没有其他人提出类似提议。

当前的环境是 1.4.0 版本，Chrome 浏览器。

### 未启用「使用快速格式化代码」模式时，意外选中没有显示的按钮

禁用「使用快速格式化代码」按钮后，从「说话人」输入框出发，要连续按 11 次 Tab 才能够到达「内容」输入框。

### 切换焦点时，会意外选中当前未显示的 section

同样的，当到达一个 `<section>` 内的最后一个元素时，再次按下 `Tab` 键，焦点会消失，而且要按很多很多很多次，才会回到页面的开头。我试着用 DevTools 把所有的 `<section>` 都显示了出来，发现确实按下 `Tab` 键的时候，会选中其他本来并不显示的页面的元素。

### 关于悬浮窗的焦点

不论是表情选择悬浮窗，还是图片选择悬浮窗，使用 `Shift+Tab` 从悬浮窗的第一个元素离开时，焦点都会消失。同样，使用 `Tab` 从最后一个元素离开时，焦点也会消失。

目前，如果焦点在表情悬浮窗，是可以按下 `Esc` 关闭的，因此希望图片悬浮窗也可以这么关闭。除此之外，希望这两个悬浮窗不能够因为 `Tab` 选择而意外失去焦点。

## 解决方案……？

或许大佬可以参考一下 [MDN web docs 上关于 tabindex 的介绍](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex)，或许这个很有用……？

**Comment by sheep-realms** [comment]
已修复，将在下个版本推送修复

**Comment by sheep-realms** [comment]
包含此修复的版本 1.4.1 已发布
