### ISSUE TITLE
编辑器启用「引用符号」时，无法发送以快速格式化代码为开头的消息

### ISSUE THREAD

**Issue by Passthem-desu** [sheep-realms/Echo-Live#28]
- 我已确认 Echo-Live 的最新发行版本中依然存在此问题。
- 我已确认近期没有其他人提出类似问题。

## 问题描述
启用了「使用快速格式化代码」和「引用符号」时，当编辑框中的输入仅包含一些格式化代码加上一串文字时，在 `ptextSubmit()` 函数中的 `__messagePackage(text)` 函数内部，由于 `text` 此时的类型是 `object`，会触发程序通过 `[before, ...text, after]` 对 `text` 进行解包。但此时，`text` 是一个段落，不能被迭代，在此处触发报错，导致消息无法发出。

示例：当输入为 `@[#e53734]@b这是红色` 时，会有 `Uncaught TypeError: text is not iterable` 的错误。

## 解决方案
一个简单的补丁是删去 `EchoLiveTools.js` 的第 289 行 `if (message.length == 1) return message[0];`。此时无论有多少个段落，返回的都是段落数组，以此保证 `__messagePackage(text)` 得到的数据都是可以解包的。

**Comment by sheep-realms** [comment]
感谢报告漏洞，已修复
