### ISSUE TITLE
[RFC] 使用node.js实现在其他终端上使用editor

### ISSUE THREAD

**Issue by TrueRou** [sheep-realms/Echo-Live#8]
- 我已确认 Echo-Live 近期没有类似更新。
- 我已确认近期没有其他人提出类似提议。

## 有关 #3 

首先, #3 中并没有提到跨设备使用editor

#3 中有提到开发后端的缺点, 其一是用户使用难度高, 鉴于nodejs也可以打包发布, 应该不会导致用户使用困难

引入后端还可以让其他开发者直接使用暴露的API, 甚至不用阅读Echo-Live的任何代码, 这会给开发灵活性带来提升

## 提议描述
目前live和editor必须在同一个设备上使用, 这对没有多显示器、或者游戏强制全屏的用户来说体验比较糟糕

如果可以在其他设备（例如手机）上使用editor, 可以大幅提升用户体验

## 实现方法
使用node,js搭建简单的后端, 将消息经由后端进行处理
局域网内的设备即可使用浏览器直接访问前端页面, 调用API发送信息

**Comment by sheep-realms** [comment]
此前已有尝试过 node.js，虽然有过一点开发经验，但仍然有很高的学习成本。此外，Echo-Live 还不完善，前不久才刚刚结束早期快速迭代的开发阶段，各个功能仍不稳定，此刻迁移容易产生很多问题。因此在我掌握必要的知识之前，暂不考虑迁移到 node.js。

**Comment by sheep-realms** [comment]
不过跨设备是个好主意，我之前从没有想过这点。

**Comment by sheep-realms** [comment]
感谢您提供的建议，我会好好考虑的。关于后端开发我现在没有明确的方向，您有什么推荐的模块或框架吗？

**Comment by TrueRou** [comment]
> 感谢您提供的建议，我会好好考虑的。关于后端开发我现在没有明确的方向，您有什么推荐的模块或框架吗？

后端开发的话用node一般选择比较轻巧的express.

另外看现在前端主要是jquery, 如果前后端分离了的话可以选择用vue, 会使开发轻巧很多.

如果有python经验的话, fastapi也是比较不错的选择, 不过引入python的话打包起来比较麻烦和冗余, 不太合理

**Comment by sheep-realms** [comment]
> > 感谢您提供的建议，我会好好考虑的。关于后端开发我现在没有明确的方向，您有什么推荐的模块或框架吗？
> 
> 后端开发的话用node一般选择比较轻巧的express.
> 
> 如果有python经验的话, fastapi也是比较不错的选择, 不过引入python的话打包起来比较麻烦和冗余, 不太合理
> 
> 另外看现在前端主要是jquery, 如果前后端分离了的话可以选择用vue, 会使开发轻巧很多.

好的，感谢提供帮助！

**Comment by sheep-realms** [comment]
虽然我不能立马搓一个后端出来，但拜你所赐我发现我可以提供一个 WebSocket 接口对接现有的广播模式，以解决离开 OBS 就没有 API 可用的燃眉之急。我认识的一些开发者也正在帮我解决这些问题，再次感谢您提供的帮助！

告知其他开发者：包含 WebSocket 接口的版本稍后会提交至 dev 分支，预计会出现在 1.2.4 版本中。

**Comment by Rickyxrc** [comment]
正巧看到了！websocket 的客户端我这里有一个正在开发的，通过设置为局域网地址就可以跨设备跑了。
https://github.com/Rickyxrc/echo-client

**Comment by Rickyxrc** [comment]
还有就是关于发展方向的问题，我认为将整个程序迁移成为一个偏服务端的程序没有太大必要，目前使用 websocket 来进行通讯是很不错的选择。
第二点就是 Node.js，这倒是个好主意，等稳定下来了可以考虑迁移，我的建议也是使用 Vue 或 React 等组件式的框架来帮助开发。

**Comment by sheep-realms** [comment]
目前已经初步实现了这个提议：https://github.com/sheep-realms/Echo-Live-WebSocket-Server
