### ISSUE TITLE
关于字体支持建议

### ISSUE THREAD

**Issue by 6078HITHEDAY** [sheep-realms/Echo-Live#9]
- 我已确认 Echo-Live 近期没有类似更新。
- 我已确认近期没有其他人提出类似提议。

## 提议描述
试试霞鹭https://github.com/lxgw/LxgwNeoXiHei-Screen

**Comment by sheep-realms** [comment]
字体可以由用户通过修改样式文件自行选择。我们可以提供一个字体推荐清单，但不会内置字体文件。
